name: CI

on: [push, pull_request, workflow_dispatch]

env:
  repo_name: ${{ github.repository }}
  sha_git: ${{ github.sha }}

jobs:
  Basic_Workflow:
    strategy:
      matrix:
        os: [
            ubuntu-18.04,
            ubuntu-20.04,
            ubuntu-22.04,
          ]
  
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Stage
        run: |
          mkdir build && cd build
          cmake -DENABLE_ADE_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j

      - name: ADE-Test Stage
        run: ./build/bin/ade-tests 

      - name: CMN-Test Stage
        run: ./build/bin/common-tests